export const matchedRoutes = {
  dashboards: "/dashboards/tasks",
  projects: "/projects",
  processes: "/processes",
  procedures: "/procedures",
  estimates: "/estimates",
  proposals: "/proposals",
  "create-notes": "/projects",
  tasks: "/tasks",
  partners: "/partners",
  invoices: "/invoices",
  expenses: "/expenses",
  payments: "/payments",
  "credit-notes": "/credit-notes",
  files: "/files",
  "report-timesheets": "report-timesheets",
  settings: "/",
  profile: "/partners",
  project: "/projects",
  customer: "/partners",
};
