name: Backend Pipeline
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Connect to server and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          script: |
            eval $(ssh-agent)
            ssh-add /home/ubuntu/.ssh/id_rsa
            cd /home/ubuntu/velo-legal
            git pull
            rm -rf vendor
            docker exec velo-legal-api php composer.phar install
            docker exec velo-legal-api php artisan migrate
