name: Staging Workflow
on:
  push:
    branches: [develop]
jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Connect to server and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST_STAGING }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_SSH_KEY_STAGING }}
          script: |
            eval $(ssh-agent)
            ssh-add /home/ubuntu/.ssh/id_rsa
            cd /var/www/velo-legal
            git pull
            cd back
            composer install
            php artisan migrate
  deploy_frontend:
    runs-on: ubuntu-latest
    needs: [deploy_backend]
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Connect to server and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST_STAGING }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_SSH_KEY_STAGING }}
          script: |
            cd /var/www/velo-legal
            cd front
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 18
            export NODE_OPTIONS="--max-old-space-size=1024"
            npm install
            npm run build
            pm2 restart all
